In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from scipy.linalg import eig

In [3]:
data=np.array([[3,4],[2,8],[6,9],[10,12]])
data

array([[ 3,  4],
       [ 2,  8],
       [ 6,  9],
       [10, 12]])

In [6]:
meanbycol=np.mean(data,axis=0)
meanbycol

array([5.25, 8.25])

In [8]:
stdbycol=np.std(data,axis=0)
stdbycol

array([3.1124749 , 2.86138079])

In [9]:
scaled_data=(data-meanbycol)/stdbycol
scaled_data

array([[-0.7228974 , -1.4852969 ],
       [-1.04418513, -0.08737041],
       [ 0.2409658 ,  0.26211122],
       [ 1.52611672,  1.31055608]])