In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from scipy.linalg import eig

In [3]:
data=np.array([[3,4],[2,8],[6,9],[10,12]])
data

array([[ 3,  4],
       [ 2,  8],
       [ 6,  9],
       [10, 12]])

In [6]:
meanbycol=np.mean(data,axis=0)
meanbycol

array([5.25, 8.25])

In [8]:
stdbycol=np.std(data,axis=0)
stdbycol

array([3.1124749 , 2.86138079])

In [9]:
scaled_data=(data-meanbycol)/stdbycol
scaled_data

array([[-0.7228974 , -1.4852969 ],
       [-1.04418513, -0.08737041],
       [ 0.2409658 ,  0.26211122],
       [ 1.52611672,  1.31055608]])

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(data)

array([[-0.7228974 , -1.4852969 ],
       [-1.04418513, -0.08737041],
       [ 0.2409658 ,  0.26211122],
       [ 1.52611672,  1.31055608]])

Calc Covariance

In [11]:
np.cov(scaled_data)

array([[ 2.90626499e-01, -3.64737533e-01, -8.06062818e-03,
         8.21716621e-02],
       [-3.64737533e-01,  4.57747206e-01,  1.01161238e-02,
        -1.03125797e-01],
       [-8.06062818e-03,  1.01161238e-02,  2.23564358e-04,
        -2.27905995e-03],
       [ 8.21716621e-02, -1.03125797e-01, -2.27905995e-03,
         2.32331947e-02]])

In [15]:
cov_mat=np.cov(scaled_data.T)
cov_mat

array([[1.33333333, 1.07605651],
       [1.07605651, 1.33333333]])

In [16]:
eig_val,eig_vec=eig(cov_mat)