Something deleted this all so rewrite this assesment

In [19]:
import pandas as pd
import numpy as np
from statistics import mode

In [36]:
data=[-19.2,23,24,32,45,12,43,67,45,32,56,32,100]

Mean Median Mode

In [21]:

mean=np.mean(data)
mode=mode(data)
median=np.median(data)

In [22]:
data_copy=data.copy()

In [23]:
data

[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

In [24]:
# custom Logic for mean
sum=0
no_of_elements=len(data)
for val in data:
    sum+=val
print(f"Mean is : {sum/no_of_elements}")

Mean is : 37.36363636363637


In [25]:
# Other Way
print(np.sum(data)/len(data))

37.36363636363637


Dispersion of Data
1.Percentile
2.standard Deviation
3.Variance

In [26]:
np.percentile(data,[25])

array([28.])

In [27]:
np.percentile(data,[25,50])

array([28., 32.])

In [28]:
np.percentile(data,[25,50,75])

array([28., 32., 45.])

In [29]:
np.percentile(data,[25,50,75,100])  # Quartile

array([28., 32., 45., 67.])

IQR  
to calculate IQR We need  q3 ,q1   calculated below

In [30]:
q3=np.percentile(data,[75])
q1=np.percentile(data,[25])
IQR=q3-q1
IQR

array([17.])

Calculate Upperbond ,lowerbond 

In [31]:
upper_bound=(q3+1.5*IQR)
lower_bound=(q1-1.5*IQR)

In [33]:
lower_bound

array([2.5])

In [32]:
upper_bound

array([70.5])

Finding Outliers 

In [37]:
outliers=[]
for val in data:
    if val>upper_bound:
        outliers.append(val)
    elif val<lower_bound:
        outliers.append(val)
print(outliers)

[-19.2, 100]


In [38]:
data

[-19.2, 23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32, 100]

Elimnating Ouliers

In [39]:
for val in outliers:
    data.remove(val)
data

[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

Variance and Standard Deviation

In [ ]:
np.var(data_copy)  # Variance 

np.float64(226.23140495867773)

In [ ]:
np.std(data_copy)   # Standard Deviation

np.float64(15.040990823701666)

Manual Logic for Variance    fromula =1/n sumation (x-mean)**2

In [42]:
data_copy

[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

In [ ]:
mean=np.mean(data_copy)
sumation=0
for v in data_copy:
    sumation+=v
variance=sumation/len(data_copy)
variance