Something deleted this all so rewrite this assesment

In [32]:
import pandas as pd
import numpy as np
from statistics import mode

In [33]:
data=[-19.2,23,24,32,45,12,43,67,45,32,56,32,100]

Mean Median Mode

In [34]:

mean=np.mean(data)
mode=mode(data)
median=np.median(data)

In [35]:
data_copy=data.copy()

In [36]:
data

[-19.2, 23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32, 100]

In [37]:
# custom Logic for mean
sum=0
no_of_elements=len(data)
for val in data:
    sum+=val
print(f"Mean is : {sum/no_of_elements}")

Mean is : 37.830769230769235


In [38]:
# Other Way
print(np.sum(data)/len(data))

37.830769230769235


Dispersion of Data
1.Percentile
2.standard Deviation
3.Variance

In [39]:
np.percentile(data,[25])

array([24.])

In [40]:
np.percentile(data,[25,50])

array([24., 32.])

In [41]:
np.percentile(data,[25,50,75])

array([24., 32., 45.])

In [42]:
np.percentile(data,[25,50,75,100])  # Quartile

array([ 24.,  32.,  45., 100.])

IQR  
to calculate IQR We need  q3 ,q1   calculated below

In [43]:
q3=np.percentile(data,[75])
q1=np.percentile(data,[25])
IQR=q3-q1
IQR

array([21.])

Calculate Upperbond ,lowerbond 

In [44]:
upper_bound=(q3+1.5*IQR)
lower_bound=(q1-1.5*IQR)

In [45]:
lower_bound

array([-7.5])

In [46]:
upper_bound

array([76.5])

Finding Outliers 

In [47]:
outliers=[]
for val in data:
    if val>upper_bound:
        outliers.append(val)
    elif val<lower_bound:
        outliers.append(val)
print(outliers)

[-19.2, 100]


In [48]:
data

[-19.2, 23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32, 100]

Elimnating Ouliers

In [49]:
for val in outliers:
    data.remove(val)
data

[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

Variance and Standard Deviation

In [50]:
# variance 
np.var(data)

np.float64(226.23140495867773)

In [51]:
#standard Deviation
np.std(data)

np.float64(15.040990823701666)

MANUAL LOGIC FOR VARIACNE CALCULATIONS


In [52]:
data

[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

In [53]:
# Population Variance 
sum=0
lengthh=len(data)

for val in data:
    sum+=(val-np.mean(data))**2
pvariance=sum/lengthh       
print(pvariance)

226.23140495867773


In [54]:
# Sample Variance 
sum=0
lengthh=len(data)

for val in data:
    sum+=(val-np.mean(data))**2
svariance=sum/(lengthh-1)      
print(svariance)

248.8545454545455


Using Statistics Libraray 

In [55]:
import statistics

In [56]:
statistics.pvariance(data)

226.23140495867767

In [57]:
statistics.variance(data)

248.85454545454544

Standard Deviation


In [58]:
# Population Standard Deviation
pstd=pvariance**0.5
pstd

np.float64(15.040990823701666)

In [59]:
# Sample Standard Deviation
samp_std=svariance**0.5
samp_std

np.float64(15.775124261144363)

Using Statistics Library finding variance


In [ ]:
statistics.stdev(data)    # sample std

15.775124261144361

In [61]:
statistics.pstdev(data)    # poplutaion std

15.040990823701664