Creating arrays One Dimensional

In [1]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])    # Method 1 
arr1=np.asarray([1,2,3,4,5,6]) # Method 2 

print(arr)
print(arr1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


Creating arrays 2 Dimensional

In [4]:
two_D=np.array([[1,2,5],[2,4,4]])
print(two_D)
print(two_D.ndim)

[[1 2 5]
 [2 4 4]]
2


Creating arrays 3 Dimensional

In [ ]:
three_D=np.array([[[1,2,3],[2,4,5]],[[1,2,1],[2,3,2]]])
print(three_D)
print(three_D.ndim)
