we will see different arrays 

In [1]:
import numpy as np

In [3]:
empty=np.empty((2,3))
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.33644129e-307, 2.67019999e-306, 9.27312161e-312]])

In [4]:
zeros=np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
ones=np.ones((5,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
specific=np.full((3,6),255)
specific

array([[255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255]])

In [9]:
identity=np.identity(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Creating A Dataframe

In [10]:
import pandas as pd

In [14]:
df=pd.DataFrame(np.random.rand(5,6),columns=["c1","c2","c3","c4","c5","c6"],index=['r1','r2','r3','r4','r5',])
df

c1        c2        c3        c4        c5        c6
r1  0.886988  0.120082  0.029265  0.786707  0.046967  0.613605
r2  0.302712  0.722644  0.307629  0.013082  0.540453  0.753752
r3  0.826659  0.812750  0.532797  0.460348  0.950257  0.094061
r4  0.979594  0.329559  0.930043  0.368129  0.413889  0.158459
r5  0.744934  0.325981  0.725441  0.539661  0.481053  0.175295

Linspace : evenly spaced values 
syntax
start end(inclusive) no_of_elemnets

In [15]:
arr1=np.linspace(0,1,10)
arr1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Logspace : Numbers spaced evenly on a log scale

In [16]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

Slicing

In [17]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [20]:
a[1:4]

array([2, 3, 4])

In [21]:
a[-2]

np.int64(4)

2d Array

In [ ]:
ab=np.array([[1,2,3],
             [4,5,6]])
ab

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
ab[:,1:3]

array([[2, 3],
       [5, 6]])

In [23]:
ab[0][1]

np.int64(2)

In [24]:
ab[0,1]

np.int64(2)

In [27]:
ab[0]

array([1, 2, 3])

In [28]:
ab[0:2,1:2]

array([[2],
       [5]])