In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
arr2=arr*2
arr2

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])*2
arr2

In [ ]:
x=np.array([1,2,3])
y=np.array([1,2,3])
x+y

In [ ]:
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6]])
x+y

In [16]:
a=np.array([[1],[2],[3]])
b=np.array([4,5,6])
a*b

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [17]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[6 6 9]
[-4 -2 -3]
[ 5  8 18]
[0.2 0.5 0.5]


Log exponentials etc

In [18]:
np.log(np.array([1,2,3]))



array([0.        , 0.69314718, 1.09861229])

In [19]:
np.exp(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [20]:
np.log10(np.array([1,2,3]))

array([0.        , 0.30103   , 0.47712125])

Different airthamatic opearations on arrays

In [21]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.add(arr1,arr2)

array([5, 7, 9])

In [22]:
np.multiply(arr1,arr2)

array([ 4, 10, 18])

In [23]:
np.divide(arr2,arr1)

array([4. , 2.5, 2. ])

In [24]:
np.subtract(arr1,arr2)

array([-3, -3, -3])

In [25]:
np.power(arr1,arr2)

array([  1,  32, 729])

Linear Algebra

In [ ]:
np.dot(arr1,arr1)    # dot product

np.int64(14)

In [29]:
#Transpose
a=np.array([[1,2],[3,4]])
b=np.array([[5,3],[7,4]])
print(a.T)  # Transpose of A
print(b.T)  # Transpose of B

[[1 3]
 [2 4]]
[[5 7]
 [3 4]]


Inversion of a Matrix

In [30]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Eigen Values and Eigen Vectors

In [ ]:
w,v=np.linalg.eig(a)
print("eigen values : ",w)
print("eigen vector : ",v)

eigen value :  [-0.37228132  5.37228132]
eigen vector :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
