Where function is used for conditional selection 

where returns indices where a condition is met


In [1]:
import numpy as np

In [2]:
array=np.array([10,20,30,20,50,80,90])

In [ ]:
indicies=np.where(array>25)   # Will Return indices where the condition is true
indicies

(array([2, 4, 5, 6]),)

In [5]:
new_array=np.where(array>25 ,1 ,0)
new_array

array([0, 0, 1, 0, 1, 1, 1])

In [8]:
matrix=np.array([[100,200,35],[44,55,60]])
result=np.where(matrix>3,'High','Low')
result

array([['High', 'High', 'High'],
       ['High', 'High', 'High']], dtype='<U4')

In [9]:
filterd_values=np.where((matrix>15)&(matrix<45),matrix,-1)
filterd_values

array([[-1, -1, 35],
       [44, -1, -1]])